var module = {"info": [
    {"name": "core-webgl", "size": "42KB", "checked": 0, "rule": ["core", "core-extensions"], "info": "Cocos2d WebGL support"},
    {"name": "core", "size": "226KB", "checked": 0, "rule": [], "info": "Engine core modules, includes Director, Node, Scene, Layer, Sprite, LabelTTF, EventManger, Scheduler and Texture2D. The default render is canvas."},
    {"name": "core-extensions", "size": "56KB", "checked": 0, "rule": ["core"], "info": "Cocos2d Core extensions"},
    {"name": 'webgl', "size": 'Unknow', "checked": 0, "rule": ['core', 'core-webgl', 'core-extensions', 'kazmath', 'shaders'], "info": 'Cocos2d WebGL renderer'},
    {"name": "debugger", "size": "16KB", "checked": 0, "rule": ["core"], "info": "Log system and debug informations"},
    {"name": "actions", "size": "52KB", "checked": 0, "rule": ["core"], "info": "Configurable actions for animating nodes with position, scale, etc"},
    {"name": "labels", "size": "19KB", "checked": 0, "rule": ["core"], "info": "Label nodes including LabelBMFont, LabelAtlas"},
    {"name": "audio", "size": "13KB", "checked": 0, "rule": ["core"], "info": "Audio system."},
    {"name": "menus", "size": "19KB", "checked": 0, "rule": ["core", "actions"], "info": "Menu and MenuItem nodes for creating game menu."},
    {"name": "transitions", "size": "23KB", "checked": 0, "rule": ["core", "actions", "render-texture", "progress-timer"], "info": "Scene transition effects"},
    {"name": "ccui", "size": "177KB", "checked": 0, "rule": ["core", "gui", "actions", "labels", "text-input", "clipping-nodes"], "info": "Cocos UI widgets with layout support"},
    {"name": "shape-nodes", "size": "16KB", "checked": 0, "rule": ["core"], "info": "DrawNode can be used to render lines, polygons, curves, etc"},
    {"name": "clipping-nodes", "size": "5KB", "checked": 0, "rule": ["core", "shape-nodes"], "info": "ClippingNode can clip hosted nodes with shape or texture as stencil"},
    {"name": "particle", "size": "65KB", "checked": 0, "rule": ["core", "compression"], "info": "ParticleSystem node and built in particle effects"},
    {"name": "progress-timer", "size": "14KB", "checked": 0, "rule": ["core", "actions"], "info": "ProgressTimer node which can transform a node into a progression bar"},
    {"name": "actions3d", "size": "22KB", "checked": 0, "rule": ["core","webgl", "core-webgl", "kazmath", "shaders", "actions", "effects", "render-texture"], "info": "Effects that can be applied to nodes, like page turn, shake, wave, etc"},
    {"name": "tilemap", "size": "34KB", "checked": 0, "rule": ["core", "compression"], "info": "TMX file parser for creating tile map layers"},
    {"name": "parallax", "size": "1KB", "checked": 0, "rule": ["core"], "info": "Parallax effect which can be applied to layers"},
    {"name": "render-texture", "size": "10KB", "checked": 0, "rule": ["core"], "info": "RenderTexture node for custom rendering"},
    {"name": "text-input", "size": "9KB", "checked": 0, "rule": ["core"], "info": "Nodes for simple text inputing"},
    {"name": "gui", "size": "92KB", "checked": 0, "rule": ["core", "clipping-nodes", "render-texture", "actions", "progress-timer"], "info": "Another GUI extension with a set of useful widgets"},
    {"name": "editbox", "size": "15KB", "checked": 0, "rule": ["core", "gui"], "info": "Edit Box for more complex text inputing"},
    {"name": "cocostudio", "size": "136KB", "checked": 0, "rule": ["core", "tilemap", "particle", "shape-nodes", "ccui"], "info": "CocoStudio editor support"},
    {"name": "ccbreader", "size": "68KB", "checked": 0, "rule": ["core", "audio", "gui", "menus", "particle", "actions", "labels"], "info": "CocosBuilder editor support"},
    {"name": "box2d", "size": "222KB", "checked": 0, "rule": ["core", "physics"], "info": "Built in box2d physics engine support"},
    {"name": "chipmunk", "size": "55KB", "checked": 0, "rule": ["core", "physics"], "info": "Built in Chipmunk physics engine support"},
    {"name": "socketio", "size": "44KB", "checked": 0, "rule": [], "info": "ScoketIO library support"},
    {"name": "pluginx", "size": "15KB", "checked": 0, "rule": ["core"], "info": "Social network API plugins"},
    {"name": "motion-streak", "size": "6KB", "checked": 0, "rule": ["core", "webgl", "core-webgl", "shaders", "kazmath", "labels"], "info": "MotionStreak which can manage a ribbon based on its motion"},

    {"name": "kazmath", "size": "30KB", "checked": 0, "rule": ["core"], "info": "Math lib for webgl"},
    {"name": "shaders", "size": "24KB", "checked": 0, "rule": ["core", "kazmath"], "info": "Shaders"},
    {"name": "node-grid", "size": "1KB", "checked": 0, "rule": ["core"], "info": "Base node of effects"},
    {"name": "effects", "size": "12KB", "checked": 0, "rule": ["core", "node-grid"], "info": "Some effects"},
    {"name": "compression", "size": "31KB", "checked": 0, "rule": ["core"], "info": "Compression of tilemap and particle"},
    {"name": "physics", "size": "5KB", "checked": 0, "rule": ["core", "shape-nodes"], "info": "Physics node for Box2d and Chipmunk"}
]};

var hiddenList = {
    'core-webgl': 1,
    'core-extensions': 1,
    'kazmath': 1,
    'shaders': 1,
    'node-grid': 1,
    'compression': 1,
    'effects': 1,
    'physics': 1
};

var _sort = [
    "core-webgl",
    "core",
    "core-extensions",
    "debugger",
    "actions",
    "audio",
    "menus",
    "kazmath",
    "shaders",
    "render-texture",
    "labels",
    "motion-streak",
    "node-grid",
    "shape-nodes",
    "clipping-nodes",
    "effects",
    "actions3d",
    "progress-timer",
    "transitions",
    "compression",
    "particle",
    "text-input",
    "tilemap",
    "parallax",
    "gui",
    "ccbreader",
    "editbox",
    "ccui",
    "cocostudio",
    "pluginx",
    "physics",
    "socketio",
    "box2d",
    "chipmunk"
];